export const HTTP = {
	FETCHING: 'FETCHING',
	FETCH_SUCCESS: 'FETCH_SUCCESS',
	FETCH_ERROR: 'FETCH_ERROR',
	POSTING: 'POSTING',
	POST_ADD_COINS_SUCCESS: 'POST_ADD_COINS_SUCCESS',
	POST_REDEEM_COINS_SUCCESS: 'POST_REDEEM_COINS_SUCCESS',
	POST_SUCCESS: 'POST_SUCCESS',
	POST_ERROR: 'POST_ERROR',
};

export const MESSAGE_REMOVE = 'MESSAGE_REMOVE';
